### ISSUE TITLE
[!] TypeError: lodash.get(...).flatMap is not a function

### ISSUE THREAD

**Issue by MaxterBattle** [crxjs/chrome-extension-tools#388]
### Build tool

Rollup

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

II am trying to get sourcemap debugging working with a simple extension.   
Building an extension after experimentally modifying the manifest, this error appears during the build.

### Reproduction

https://github.com/MaxterBattle/TrialExtension/tree/debugging

### Logs

```shell
> ts-extension-starter@1.0.0 build
> rollup -c


src/manifest.json → dist...
[!] TypeError: lodash.get(...).flatMap is not a function
TypeError: lodash.get(...).flatMap is not a function
    at deriveFilesMV3 (C:\Code\TrialExtension\node_modules\rollup-plugin-chrome-extension\src\manifest-input\manifest-parser\index.ts:50:1)
    at deriveFiles (C:\Code\TrialExtension\node_modules\rollup-plugin-chrome-extension\src\manifest-input\manifest-parser\index.ts:30:1)
    at Object.options (C:\Code\TrialExtension\node_modules\rollup-plugin-chrome-extension\src\manifest-input\index.ts:215:1)
    at Object.options (C:\Code\TrialExtension\node_modules\rollup-plugin-chrome-extension\src\index.ts:60:1)  
    at C:\Code\TrialExtension\node_modules\rollup\dist\shared\rollup.js:23869:43
    at getInputOptions (C:\Code\TrialExtension\node_modules\rollup\dist\shared\rollup.js:23862:61)
    at rollupInternal (C:\Code\TrialExtension\node_modules\rollup\dist\shared\rollup.js:23807:72)
    at build (C:\Code\TrialExtension\node_modules\rollup\dist\bin\rollup:1528:20)
    at runRollup (C:\Code\TrialExtension\node_modules\rollup\dist\bin\rollup:1668:21)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 18.38 GB / 31.89 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 2.4.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.22621.1
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
@MaxterBattle This error makes me think `lodash.get(...)` isn't returning an array. 

Looking at [the manifest](https://github.com/MaxterBattle/TrialExtension/blob/1b45d96d75e411737f08df3f7478b547dc4560f0/src/manifest.json#L22-L28), `web_accessible_resources` is an object:

```json
{
  "web_accessible_resources": {
    "resources": [
        "pages/popup/index.html",
        "pages/popup/App.tsx",
        "pages/popup/index.tsx"
    ]
  }
}
``` 

I'm surprised the validator didn't catch this, but it should work if you make it an array. 👍

```json
{
  "web_accessible_resources": [{
    "resources": [
        "pages/popup/index.html",
        "pages/popup/App.tsx",
        "pages/popup/index.tsx"
    ]
  }]
}
``` 

### Resources

[Manifest - Web Accessible Resources - Chrome Developers](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/#manifest-declaration)
