### ISSUE TITLE
The paths specified in the manifest are not resolved correctly

### ISSUE THREAD

**Issue by GoodSimonVM** [crxjs/chrome-extension-tools#455]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

I have configured `rootDir` in `tsconfig.json` and `root` in `vite.config.ts`, but in the manifest I still have to write paths relative to the root of the project. If I specify a path relative to the root specified in the configuration, for example `"default_popup": "pages/popup/index.html"` (without `src/`), then I get an error:
```sh
Could not resolve entry module (pages/popup/index.html).
error during build:
Error: Could not resolve entry module (pages/popup/index.html).
    at error (file:///D:/Projects/chrome-extension/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.loadEntryModule (file:///D:/Projects/chrome-extension/node_modules/rollup/dist/es/shared/rollup.js:22352:20)
    at async Promise.all (index 0)
```
If I specify the path along with `src/`, then after the build my `src/pages/popup/index.html` will be placed in `dist/pages/popup/index.html`, but the path in the output `manifest.json` file will be `src/pages/popup/index.html`. So this is a error, because the path `dist/src/pages/popup/index.html` doesn't exist and `chrome` can't load this popup page.

### Reproduction

Use this minimal example: [chrome-extension.zip](https://github.com/crxjs/chrome-extension-tools/files/9209976/chrome-extension.zip)

### Logs

```sh
PS D:\Projects\chrome-extension> npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> chrome-extension@0.0.1 build
> vue-tsc --noEmit && vite build

vite v3.0.3 building for production...
✓ 2 modules transformed.
Could not resolve entry module (pages/popup/index.html).
error during build:
Error: Could not resolve entry module (pages/popup/index.html).
    at error (file:///D:/Projects/chrome-extension/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.loadEntryModule (file:///D:/Projects/chrome-extension/node_modules/rollup/dist/es/shared/rollup.js:22352:20)
    at async Promise.all (index 0)
```

### System Info

```shell
System:
  OS: Windows 10 10.0.19042
  CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
  Memory: 5.58 GB / 15.86 GB
Binaries:
  Node: 16.15.1 - D:\Programs\nodejs\node.EXE
  npm: 8.15.1 - D:\Programs\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.423.0), Chromium (103.0.1264.71)
  Internet Explorer: 11.0.19041.1
npmPackages:
  @crxjs/vite-plugin: ^1.0.13 => 1.0.13
  vite: ^3.0.3 => 3.0.3
```

### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
@GoodSimonVM Thanks for the great repro! I'll put this on the roadmap, until then PR's are welcome 👍
