### ISSUE TITLE
Cannot set properties of undefined (setting 'isSelfAccepting')

### ISSUE THREAD

**Issue by asqwrd** [crxjs/chrome-extension-tools#518]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

I am getting the following error when using `vite-plugin-svgr` in my vite app.  This only happens when I run vite dev.  The app builds fine with `vite build`

![image](https://user-images.githubusercontent.com/6006433/193160811-39b40226-07c1-4998-ab39-0a17333b6dda.png)

### Reproduction

1. Create a react vite app.  
2. Import an svg file in the app like so: `import { ReactComponent as CloseIcon } from "theme/images/icon-close.svg";`
3. Run vite dev

### Logs

```shell
VITE v3.1.0  ready in 1206 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
4:41:49 PM [crx] error from file writer:
Error: Could not load /src-theme-images-joggo-comma_black.svg-DL21e.js (imported by ../../../../../../src-components-NotificationToast-NotificationToast.tsx-76mNM.js): Cannot set properties of undefined (setting 'isSelfAccepting')
    at TransformContext.transform (file:///Users/asqwrd/code/summari-monorepo/apps/summari-extension/node_modules/vite/dist/node/chunks/dep-665b0112.js:37466:48)
    at async Object.transform (file:///Users/asqwrd/code/summari-monorepo/apps/summari-extension/node_modules/vite/dist/node/chunks/dep-665b0112.js:41031:30)
    at async loadAndTransform (file:///Users/asqwrd/code/summari-monorepo/apps/summari-extension/node_modules/vite/dist/node/chunks/dep-665b0112.js:37292:29)
4:41:53 PM [vite] ✨ optimized dependencies changed. reloading
```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.11 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.19.1 - ~/code/summari-monorepo/node_modules/.bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Browsers:
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    vite: ^3.1.0 => 3.1.0
```

### Severity

blocking all usage of RPCE

**Comment by myktra** [comment]
I've had similar hiccups like this running `vite dev` with vite@3. Right now, this solution appears to work reliably with vite@2 only. See #462, #454, #427.
