### ISSUE TITLE
error: Duplicate injected file

### ISSUE THREAD

**Issue by plusminushalf** [crxjs/chrome-extension-tools#617]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

I am trying to polyfill Node.js built-in modules, reference: https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2

I am running into this problem:
```
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js" 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js" 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
Build failed with 6 errors:
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
...
```
![image](https://user-images.githubusercontent.com/5251472/208988739-8ea052e5-d993-416f-b250-43bd4cb4d13f.png)

My Vite config file: https://gist.github.com/plusminushalf/33d3d8a45b2924c846348f3f0ace17d5

### Reproduction

Clone repo: https://github.com/plusminushalf/epf-wallet/tree/main/packages/extension

Run `yarn workspace @epf-wallet/extension run dev`

### Logs

```shell
Debugger listening on ws://127.0.0.1:51088/58da7da4-dddd-45a0-8b73-b51e721c9068
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
yarn run v1.22.19
$ vite
Debugger listening on ws://127.0.0.1:51096/75b078aa-b7f7-40f2-8e78-577ccd2e3644
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[plugin:crx:manifest-loader] context method emitFile() is not supported in serve mode. This plugin is likely not vite-compatible.
 
  VITE v3.2.5  ready in 590 ms
 
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
Build failed with 6 errors:
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
...
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
 
✘ [ERROR] Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
 
19:31:30 [vite] error while updating dependencies:
Error: Build failed with 6 errors:
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js"
error: Duplicate injected file "../../node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js"
...
    at failureErrorWithLog (/Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/plusminushalf/dev/epf-wallet/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
There is a new version of the pre-bundle for "/Users/plusminushalf/dev/epf-wallet/packages/extension/node_modules/.vite/deps/preact_debug.js?v=394f032c", a page reload is going to ask for it.
There is a new version of the pre-bundle for "/Users/plusminushalf/dev/epf-wallet/packages/extension/node_modules/.vite/deps/preact.js?v=3518941b", a page reload is going to ask for it.
There is a new version of the pre-bundle for "/Users/plusminushalf/dev/epf-wallet/packages/extension/node_modules/.vite/deps/preact_jsx-dev-runtime.js?v=394f032c", a page reload is going to ask for it.
There is a new version of the pre-bundle for "/Users/plusminushalf/dev/epf-wallet/packages/extension/node_modules/.vite/deps/preact_devtools.js?v=394f032c", a page reload is going to ask for it.
There is a new version of the pre-bundle for "/Users/plusminushalf/dev/epf-wallet/packages/extension/node_modules/.vite/deps/preact_hooks.js?v=8160b146", a page reload is going to ask for it.
```

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 137.27 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 108.0.5359.124
    Safari: 16.2
```

### Severity

blocking all usage of RPCE

**Comment by zhbyak** [comment]
I had met the same problem , could please tell me how did you solve this problem? thanks a lot.My gmail: pingqian1991@gmai.com
