### ISSUE TITLE
[crx] error from file writer

### ISSUE THREAD

**Issue by a-bormark** [crxjs/chrome-extension-tools#639]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

Error message after running `yarn dev` which basically starts vite dev server. 

### Reproduction

```
import {fileURLToPath, URL} from "node:url"
import {defineConfig} from "vite"
import vue from "@vitejs/plugin-vue"
import {crx} from "@crxjs/vite-plugin"
import manifest from "./src/manifest/manifest.json"
import packageJson from "./package.json"
import vuetify from 'vite-plugin-vuetify'

manifest.version = packageJson.version

// https://vitejs.dev/config/
export default defineConfig({
	optimizeDeps: {
		include: ["webextension-polyfill"],
	},
	build: {
		commonjsOptions: {
			transformMixedEsModules: true,
		},
	},
	plugins: [
		vue(),
		vuetify({autoImport: true, styles: 'none'}),
		crx({manifest})
	]
})

```

### Logs

```shell
VITE v3.2.5  ready in 812 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
2:23:45 PM [vite] ✨ optimized dependencies changed. reloading
2:23:45 PM [crx] error from file writer:
Error: Could not load /id-__x00____void__-ACYRi.js (imported by ../../../../../../../../node_modules-.vite-deps-vuetify_lib_components_VBadge_index__mjs.js-Kp3qr.js): Unable to load "__x00____void__" from server.
    at Object.load (C:\Users\...\node_modules\@crxjs\vite-plugin\dist\index.cjs:284:17)
    at async C:\Users\...\node_modules\rollup\dist\shared\rollup.js:22050:98
    at async Queue.work (C:\Users\...\node_modules\rollup\dist\shared\rollup.js:22989:32)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 2.22 GB / 15.82 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.119
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @crxjs/vite-plugin: ^1.0.14 => 1.0.14 
    vite: 3.2.5 => 3.2.5
```

### Severity

blocking all usage of RPCE

**Comment by a-bormark** [comment]
Upgrading to "@crxjs/vite-plugin": "^2.0.0-beta.11" and "vite": "^4.0.0" helped.
