### ISSUE TITLE
[plugin externalize-deps] Failed to resolve entry for package "@crxjs/vite-plugin"

### ISSUE THREAD

**Issue by astoilkov** [crxjs/chrome-extension-tools#660]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

An error is thrown while following the [Getting Started](https://crxjs.dev/vite-plugin/getting-started/solid/create-project) guide (when I run `yarn dev`).

There is another similar issue but that one is for Vite 3 (not 4) — https://github.com/crxjs/chrome-extension-tools/issues/454.

### Reproduction

I think that following the getting started guide and installing Vite 4 should reproduce the error.

### Logs

```shell
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@crxjs/vite-plugin". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/esbuild/lib/main.js:1365:27:
      1365 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///Users/user/Temp/vite-solid-crxjs/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22005:11)
    at resolvePackageEntry (file:///Users/user/Temp/vite-solid-crxjs/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22002:5)
    at tryNodeResolve (file:///Users/user/Temp/vite-solid-crxjs/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21737:20)
    at file:///Users/user/Temp/vite-solid-crxjs/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62292:40
    at requestCallbacks.on-resolve (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1365:28)
    at handleRequest (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:727:19)
    at handleIncomingPacket (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:749:7)
    at Socket.readFromStdout (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/user/Temp/vite-solid-crxjs/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62281:27)
    at handlePlugins (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:780:5)
    at /Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:2131:14)
    at build (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1978:51)
    at bundleConfigFile (file:///Users/user/Temp/vite-solid-crxjs/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62245:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.js:3:20:
      3 │ import { crx } from '@crxjs/vite-plugin'
        ╵                     ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./manifest.json"

    vite.config.js:4:21:
      4 │ import manifest from './manifest.json'
        ╵                      ~~~~~~~~~~~~~~~~~

failed to load config from /Users/user/Temp/vite-solid-crxjs/vite.config.js
error when starting dev server:
Error: Build failed with 2 errors:
node_modules/esbuild/lib/main.js:1365:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@crxjs/vite-plugin". The package may have incorrect main/module/exports specified in its package.json.
vite.config.js:4:21: ERROR: Could not resolve "./manifest.json"
    at failureErrorWithLog (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/user/Temp/vite-solid-crxjs/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```


### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 55.45 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 106.0.5
    Safari: 16.3
  npmPackages:
    @crxjs/vite-plugin: ^2.0.0-beta.14 => 2.0.0-beta.14
    vite: ^4.0.4 => 4.0.4
```

### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
@astoilkov We've seen this error before, but I can't reproduce it with `npm init vite@latest` right now. 

Here's a working example of CRXJS with Vite 4 and React: https://github.com/crxjs/vite-4-react

The solution to this error with [Vite and SolidJS](https://github.com/crxjs/chrome-extension-tools/issues/567#issuecomment-1304843039) was to add `"type": "module"` to the `package.json`.

Hope this helps

**Comment by svicalifornia** [comment]
@jacksteamdev Thanks for the tip about `"type": "module"` in the package.json file. That fixed the issue for me with Vite and Solid.

Please add that step to the Vite CRXJS docs: https://crxjs.dev/vite-plugin/getting-started/solid/create-project

**Comment by joukhar** [comment]
"type": "module" fixed the issue
