### ISSUE TITLE
"npm run dev" works but not "npm run build"Can't build the extension for production 

### ISSUE THREAD

**Issue by esphoenixc** [crxjs/chrome-extension-tools#669]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

running `npm run dev` works fine. I see my content script working as intended.

However, running `npm run build` for production. The error is being thrown in content script.

![image](https://user-images.githubusercontent.com/84483515/225179967-dcb882c8-8556-4671-9e02-90fe474455de.png)

I strongly believe this error is coming from contents script as it was the page's devtool. Also, poopup and background.js were working fine.

The build is successful. "npm run build" does not throw any errors. However, content script is throwing the error above which prevents me from using content script to load the vue instance onto the page's DOM.

### Reproduction

![image](https://user-images.githubusercontent.com/84483515/225180076-70b827cf-8704-4e69-99b4-cb6b3d7575bf.png)

### Logs

```shell
TypeError: Cannot read properties of null (reading 'define')
    at _plugin-vue_export-helper.2706d53b.js:5:70
    at _plugin-vue_export-helper.2706d53b.js:5:85
    at __decorate (_plugin-vue_export-helper.2706d53b.js:1:74673)
    at _plugin-vue_export-helper.2706d53b.js:267:4095
```

### System Info

```shell
TypeError: Cannot read properties of null (reading 'define')
    at _plugin-vue_export-helper.2706d53b.js:5:70
    at _plugin-vue_export-helper.2706d53b.js:5:85
    at __decorate (_plugin-vue_export-helper.2706d53b.js:1:74673)
    at _plugin-vue_export-helper.2706d53b.js:267:4095
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
There's no minimal reproduction, so I can't be sure, but my guess is that this is due to [custom elements not being implemented in content scripts](https://stackoverflow.com/questions/30022350/registering-a-custom-element-from-a-chrome-extension).

The Vite error overlay uses custom elements, so CRXJS includes them in the dev build. You'll need to add a custom elements polyfill for the production build:

```
// do this in your main content script file
import '@webcomponents/custom-elements'
```

This should be documented, PRs are welcome 🌟
