### ISSUE TITLE
Build Error: [crx:manifest-post] Unexpected token s in JSON at position 0

### ISSUE THREAD

**Issue by xneworlds** [crxjs/chrome-extension-tools#760]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

When using both `@sentry/vite-plugin` and `@crxjs/vite-plugin` at the same time, the error occurs during build. If `@sentry/vite-plugin` is disabled, there will be no error. 

### Reproduction

Because the sentry configuration involves sensitive information, reproduction cannot be provided.

### Logs

```shell
[crx:manifest-post] Unexpected token s in JSON at position 0
error during build:
SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
at Object.decodeManifest (file:///Users/.../node_modules/.pnpm/@crxjs+vite-plugin@2.0.0-beta.18/node_modules/@crxjs/vite-plugin/dist/index.mjs:91:21)
    at Object.generateBundle (file:///Users/.../node_modules/.pnpm/@crxjs+vite-plugin@2.0.0-beta.18/node_modules/@crxjs/vite-plugin/dist/index.mjs:1595:40)
    at file:///Users/.../node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22748:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 4.85 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    pnpm: 8.6.10 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.102
    Safari: 16.5.1
  npmPackages:
    @crxjs/vite-plugin: 2.0.0-beta.18 => 2.0.0-beta.18 
    @sentry/vite-plugin: ^2.5.0 => 2.5.0
    vite: ^3.2.5 => 3.2.6
```

### Severity

blocking all usage of RPCE

**Comment by chronicIntrovert** [comment]
Also seeing this when including @sentry/vite-plugin.

**Comment by flexchar** [comment]
Ended up same with trying to publish source maps to Sentry

**Comment by xneworlds** [comment]
> Ended up same with trying to publish source maps to Sentry. @xneworlds have you had success with this?

I was unable to solve the problem through the plugin, but I achieved my goal by manually uploading source maps using sentry-cli.

**Comment by fbjorn** [comment]
I'm also getting this error while setting this in my Vite config:
```js
build: {
    rollupOptions: {
           output: {
                inlineDynamicImports: true,
          },
    }
  },
```

**Comment by juliankolbe** [comment]
for those still struggling with this, i dug through the sentry plugin and found that it injects a debugId IFFE into the manifest.js file and there is no way to prevent that.

this vite hack will solve that issue for you:

```
// Custom plugin to modify the Sentry plugin's renderChunk function
  {
    name: 'modify-sentry-plugin',
    enforce: 'post', // Ensure it runs after other plugins
    configResolved(config) {
      // Loop through the plugins and find the Sentry plugin that has Rollup hooks
      config.plugins.forEach((plugin: any) => {
        if (plugin.name === 'sentry-vite-debug-id-injection-plugin') {
          // Check if the plugin has the renderChunk hook (as it is a Rollup hook)
          if (plugin.renderChunk) {
            // Store the original renderChunk handler
            const originalRenderChunk = plugin.renderChunk;

            // Overwrite the renderChunk function
            plugin.renderChunk = async function (code, chunk, ...args) {
              // Skip processing the manifest file
              if (chunk.fileName.includes('crx-manifest')) {
                return null; // Skip the chunk
              }

              // Call the original renderChunk function for other files
              return originalRenderChunk.call(this, code, chunk, ...args);
            };
          }
        }
      });
    },
  },
```

**Comment by rayanSid10** [comment]
https://github.com/crxjs/chrome-extension-tools/issues/760#issuecomment-2365209487
@juliankolbe Thanks for sharing this workaround! I tried implementing the custom plugin, and while the build completes successfully, the stack traces on Sentry still appear to be obfuscated. It seems like manually uploading the source maps might be the best approach.

**Comment by SYM01** [comment]
> for those still struggling with this, i dug through the sentry plugin and found that it injects a debugId IFFE into the manifest.js file and there is no way to prevent that.
> 
> this vite hack will solve that issue for you:
> 
> ```
> // Custom plugin to modify the Sentry plugin's renderChunk function
>   {
>     name: 'modify-sentry-plugin',
>     enforce: 'post', // Ensure it runs after other plugins
>     configResolved(config) {
>       // Loop through the plugins and find the Sentry plugin that has Rollup hooks
>       config.plugins.forEach((plugin: any) => {
>         if (plugin.name === 'sentry-vite-debug-id-injection-plugin') {
>           // Check if the plugin has the renderChunk hook (as it is a Rollup hook)
>           if (plugin.renderChunk) {
>             // Store the original renderChunk handler
>             const originalRenderChunk = plugin.renderChunk;
> 
>             // Overwrite the renderChunk function
>             plugin.renderChunk = async function (code, chunk, ...args) {
>               // Skip processing the manifest file
>               if (chunk.fileName.includes('crx-manifest')) {
>                 return null; // Skip the chunk
>               }
> 
>               // Call the original renderChunk function for other files
>               return originalRenderChunk.call(this, code, chunk, ...args);
>             };
>           }
>         }
>       });
>     },
>   },
> ```
> 
> add this as its own plugin below the sentry plugin

This doesn't work for my case. But it works after changing `chunk.fileName` to `chunk.name`.
Thank @juliankolbe ! you save my life.

```typescript
{
  name: 'modify-sentry-plugin',
  enforce: 'post', // Ensure it runs after other plugins
  configResolved(config) {
    // Loop through the plugins and find the Sentry plugin that has Rollup hooks
    config.plugins.forEach((plugin: any) => {
      if (plugin.name == 'sentry-vite-debug-id-injection-plugin') {
        // Check if the plugin has the renderChunk hook (as it is a Rollup hook)
        if (plugin.renderChunk) {
          // Store the original renderChunk handler
          const originalRenderChunk = plugin.renderChunk;

          // Overwrite the renderChunk function
          plugin.renderChunk = async function (code, chunk, ...args) {
            // Skip processing the manifest file
            if (chunk.name.includes('crx-manifest')) {
              return null; // Skip the chunk
            }

            // Call the original renderChunk function for other files
            return originalRenderChunk.call(this, code, chunk, ...args);
          };
        }
      }
    });
  },
}
```
