### ISSUE TITLE
inject.js error

### ISSUE THREAD

**Issue by ultimateshadsform** [crxjs/chrome-extension-tools#856]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [X] In the terminal

### Describe the bug

When using a Vite plugin such as [Vue Devtools](https://devtools-next.vuejs.org/guide/vite-plugin) it says this error: 

```txt
http://localhost:8888/__devtools__/
Denying load of chrome-extension://pbcpfbcibpcbfbmddogfhcijfpboeaaf/inject.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
```

When I try to add `inject.js` to the array it says the file doesn't exist and that's true.

```ts
import { defineManifest } from '@crxjs/vite-plugin'
// @ts-ignore
import packageJson from './package.json'

const { version, name, description, displayName } = packageJson
// Convert from Semver (example: 0.1.0-beta6)
const [major, minor, patch, label = '0'] = version
  // can only contain digits, dots, or dash
  .replace(/[^\d.-]+/g, '')
  // split into version parts
  .split(/[.-]/)

export default defineManifest(async (env) => ({
  name: env.mode === 'staging' ? `[INTERNAL] ${name}` : displayName || name,
  description,
  // up to four numbers separated by dots
  version: `${major}.${minor}.${patch}.${label}`,
  // semver is OK in "version_name"
  version_name: version,
  manifest_version: 3,
  // key: 'ekgmcbpgglflmgcfajnglpbcbdccnnje',
  action: {
    default_popup: 'src/popup/index.html',
  },
  background: {
    service_worker: 'src/background/index.ts',
  },
  content_scripts: [
    {
      all_frames: false,
      js: ['src/content-script/index.ts'],
      matches: ['*://*/*'],
      run_at: 'document_end',
    },
  ],
  host_permissions: ['*://*/*'],
  options_page: 'src/options/index.html',
  permissions: ['storage'],
  web_accessible_resources: [
    {
      matches: ['*://*/*'],
      resources: ['src/content-script/iframe/index.html'],
      use_dynamic_url: true,
    },
    {
      resources: ['inject.js'],
      matches: [
        'http://localhost/*',
        'http://localhost:8888/*',
        'http://127.0.0.1/*',
        'http://127.0.0.1:8888/*',
      ],
      use_dynamic_url: true,
    },
  ],
}))

```

How can I tell crxjs to allow it since it is injected by Vite?

It's a file Vite generates and not a file which I have created myself.

![image](https://github.com/crxjs/chrome-extension-tools/assets/151234273/db0b11ef-3923-4933-b61e-7a1fcc6667cc)

### Reproduction

https://github.com/mubaidr/vite-vue3-chrome-extension-v3

### Logs

```shell
Vue DevTools: Press Alt(⌥)+Shift(⇧)+D in App to toggle the Vue DevTools

  ➜  press h to show help

🌼   daisyUI 4.5.0
├─ ✔︎ 2 themes added            https://daisyui.com/docs/themes
╰─ ★ Star daisyUI on GitHub     https://github.com/saadeghi/daisyui


🌼   daisyUI 4.5.0
├─ ✔︎ 2 themes added            https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui

01:24:20 [vite] manifest.config.ts changed, restarting server...
01:24:21 [vite] server restarted.
Error: ENOENT: Could not load manifest asset "inject.js".
Manifest assets must exist in one of these directories:
Project root: "C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3"
Public dir: "C:\Users\shadow\Desktop\Coding\vite-vue3-chrome-extension-v3\public"
    at file:///C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3/node_modules/.pnpm/@crxjs+vite-plugin@2.0.0-beta.21/node_modules/@crxjs/vite-plugin/dist/index.mjs:1698:23
    at Array.map (<anonymous>)
    at Object.generateBundle (file:///C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3/node_modules/.pnpm/@crxjs+vite-plugin@2.0.0-beta.21/node_modules/@crxjs/vite-plugin/dist/index.mjs:1692:50)
    at async Bundle.generate (file:///C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:15990:9)
    at async file:///C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:23754:27
    at async catchUnfinishedHookActions (file:///C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:23088:20)
    at async start (file:///C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3/node_modules/.pnpm/@crxjs+vite-plugin@2.0.0-beta.21/node_modules/@crxjs/vite-plugin/dist/index.mjs:543:3)
    at async Server.<anonymous> (file:///C:/Users/shadow/Desktop/Coding/vite-vue3-chrome-extension-v3/node_modules/.pnpm/@crxjs+vite-plugin@2.0.0-beta.21/node_modules/@crxjs/vite-plugin/dist/index.mjs:945:13) {
  code: 'PLUGIN_ERROR',
  plugin: 'crx:manifest-post',
  hook: 'generateBundle'
}
PS C:\Users\shadow\Desktop\Coding\vite-vue3-chrome-extension-v3>
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 5.19 GB / 15.94 GB
  Binaries:
    Node: 20.10.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.2.5 - ~\scoop\apps\nodejs-lts\current\bin\npm.CMD
    pnpm: 8.14.0 - ~\scoop\shims\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
```

### Severity

annoyance

**Comment by ultimateshadsform** [comment]
I also would like to add it would be nice if these build tings only applied on dev mode.

**Comment by ultimateshadsform** [comment]
I think it was something else. Forget it.
