### ISSUE TITLE
Example won't work on firefox

### ISSUE THREAD

**Issue by renyuneyun** [crxjs/chrome-extension-tools#882]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

After following the instruction to create a new project and loaded into browser, the extension won't actually load correctly. Clicking on the icon will show the following page:

![image](https://github.com/crxjs/chrome-extension-tools/assets/3293723/a749d896-4fa7-4985-8f91-3a0b58568b69)

Error messages appear in browser console (see below).

### Reproduction

- Follow [instruction to create a new vite project](https://crxjs.dev/vite-plugin/getting-started/vanilla-js/create-project)
- Change build target to firefox by setting `plugins: [crx({ manifest, browser: 'firefox' })],` in `vite.config.js` (saw this by seeing [this post](https://github.com/crxjs/chrome-extension-tools/pull/776#issuecomment-1734039363))
- Build the extension (`npm run dev`) 
- Load the extension to Firefox (`about:debugging#/runtime/this-firefox` -- select "load temporary extension" -- select the manifest file in `dist/` directory)
- Open browser console (and switch to "multi process" page)

### Logs

```shell
Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at http://localhost:5173/@vite/env from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'” service-worker-loader.js:1:1
Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at http://localhost:5173/@vite/env from being executed because it violates the following directive: “script-src 'self'” service-worker-loader.js:1:1
Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at http://localhost:5173/@crx/client-worker from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'” service-worker-loader.js:2:1
Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at http://localhost:5173/@crx/client-worker from being executed because it violates the following directive: “script-src 'self'” service-worker-loader.js:2:1
Uncaught (in promise) TypeError: error loading dynamically imported module: http://localhost:5173/@vite/env
    <anonymous> moz-extension://6c920f88-52e6-4b5a-bc9e-33003968c870/service-worker-loader.js:1
service-worker-loader.js:1:1
Uncaught (in promise) TypeError: error loading dynamically imported module: http://localhost:5173/@crx/client-worker
    <anonymous> moz-extension://6c920f88-52e6-4b5a-bc9e-33003968c870/service-worker-loader.js:2
```

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.78 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 124.0.6367.119
    Edge: 124.0.2478.80
    Safari: 17.1
  npmPackages:
    @crxjs/vite-plugin: ^2.0.0-beta.23 => 2.0.0-beta.23 
    vite: ^5.2.0 => 5.2.11


Also

  Firefox: 125.0.3
  Firefox Developer Edition: 126.0b9
```

### Severity

blocking all usage of RPCE

**Comment by jhholm** [comment]
Firefox doesn't allow remote code exection when using manifest version 3. Localhost is technically a external/remote source, as you are loading the extension from the directory. [See mv3 migration guide](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/#content-security-policies)

You can run **vite build --watch** when developing for Firefox. It's not as nice as just running **vite-dev** for Chromium browsers with HMR. I'm using [**web-ext**](https://github.com/mozilla/web-ext) to automatically start Firefox with the extension and autoreload on changes.

**Comment by dotproto** [comment]
Thanks for sharing the info about `vite build --watch`, @jhholm. I for one wasn't familiar with that command.

[Bug 1864284](https://bugzilla.mozilla.org/show_bug.cgi?id=1864284) appears to be the relevant feature request for Firefox. In [comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1864284#c3), @Rob--W indicated that he's "leaning towards … allowing localhost and 127.0.0.1 for temporarily loaded add-ons only." Until someone is able to land that change, `vite build -- watch` should at least unblock @crxjs/vite-plugin users.

**Comment by allcentury** [comment]
@dotproto / @jhholm would either of you mind sharing your vite config?  I've tried for the last hour setting this up but have been unable to get it to work with `--watch` (works fine without it).  My config:

```ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { crx } from '@crxjs/vite-plugin';
import * as fs from 'fs';

export default defineConfig(() => {
  const browser = process.env.BROWSER || 'chrome';
  console.log('Building for', browser);

  // Load the appropriate manifest file synchronously
  const manifestPath = `./manifest.${browser}.json`;
  if (!fs.existsSync(manifestPath)) {
    throw new Error(`Manifest file for ${browser} does not exist at ${manifestPath}`);
  }
  const manifest = require(manifestPath);

  return {
    plugins: [
      react(),
      crx({ manifest }),
    ],
    build: {
      outDir: `dist/${browser}`,
    },
  };
});
```

I am able to run:

```
 BROWSER=firefox npx vite build --mode development
```

but when I run

```
BROWSER=firefox npx vite build --watch --mode development
```

I get 

```
build started...
✓ 2 modules transformed.
Could not resolve entry module (../../../../@vite/client).
```
